[package]
name = "project"
version = "0.1.0"
authors = ["Flynn Dreilinger <flynnd@stanford.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[profile.release]
lto = true

# The features section is used to select the target board.
[features]
default = []
bsp_rpiA = []

[dependencies]

# the profile used for `cargo build`
[profile.dev]
panic = "abort" # disable stack unwinding on panic

# the profile used for `cargo build --release`
# [profile.release]
# panic = "abort" # disable stack unwinding on panic